name = "MyStatsPackage"
uuid = "d5473728-f4ec-4463-babc-0d67b9f3be70"
authors = ["Hamish Hunter <u7498619@anu.edu.au> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
